package com.multi.matchon.common.domain;

public enum PositionName {
    GOALKEEPER,
    CENTER_BACK,
    LEFT_RIGHT_BACK,
    LEFT_RIGHT_WING_BACK,
    CENTRAL_DEFENSIVE_MIDFIELDER,
    CENTRAL_MIDFIELDER,
    CENTRAL_ATTACKING_MIDFIELDER,
    LEFT_RIGHT_WING,
    STRIKER_CENTER_FORWARD,
    SECOND_STRIKER,
    LEFT_RIGHT_WINGER
}
